### ISSUE TITLE
Support for parent proxy

### ISSUE THREAD

**Issue by MA-Heshmatkhah** [9seconds/mtg#113]
Hi,

In some countries like Iran, MTProto traffic has been blocked using Deep Packet Inspection, So we can't connect to MTProto Proxies outside Iran and if the proxy be in Iran, the proxy itself can't connect to Telegram's servers. so it will be great if you add support for parent -none MTProto- proxies, like SOCKS or HTTP proxy.

**Comment by pexcn** [comment]
Try new tls mode?

**Comment by 9seconds** [comment]
I see a use case, thanks. @pexcn already mentioned that it worth to try tls mode first but if you have a problem with `proxy <-> telegram` connectivity, this won't help.

Could you please consider using https://www.v2ray.com/en/ instead of this proxy? I feel that it help you better

Anyway, I would really like to avoid proxy chaining. One of the reasons is that having a proxy chain will immediately start the development of poor-man v2ray. It would be much better to contribute to v2ray instead of making yet another one.
