### ISSUE TITLE
Leaking memory

### ISSUE THREAD

**Issue by ice2heart** [9seconds/mtg#124]
Hello,

I use 2 instances of mtg on my VPS with 1gb of memory. The MTG stop transferring previews from Youtube after 24 hours of working. Other messages and pictures works fine. The restart fixed the problem. Before restart instance of the mtg took 300mb of memory.
Version: "0.16-111-g19efcc9 (go version go1.13.4 linux / amd64)" (latest docker image)

I can provide any debug information.

**Comment by 9seconds** [comment]
Do you run your proxies with adtag or without?

**Comment by ice2heart** [comment]
Yep. Both run with the same adtag.

**Comment by 9seconds** [comment]
It looks like telegram has stopped to respond to that socket for some reason. Since there was no reconnect, it also means that it didn't ask to close the connection. I've seen such behavior in the past but failed to catch it and debug.

As mitigation, I plan to do some force reconnects until I'll find a real reason for such behavior. At this certain moment you can run this proxy without adtag. Direct mode has no such flaw.

**Comment by ice2heart** [comment]
But all other stuff still working. Or it's using another socket?
![image](https://user-images.githubusercontent.com/1985165/70438499-4562c300-1a8e-11ea-89c9-197335a02283.png)

**Comment by 9seconds** [comment]
Telegram has a notion of datacenters. Every time when a client wants to send an RPC request, it specifies a DC to connect to. Some DCs are responsible for getting blobs (when you send some files), some - profile information, some - pictures, etc. Every client also makes about 3-6 connections to the proxy depending on the workload. If you do not have any media, downloads etc, then client usually requires about 2 connections to different DCs.
