### ISSUE TITLE
Starting, but can't connect

### ISSUE THREAD

**Issue by haoren61** [9seconds/mtg#131]
Hello! I'd generated a secret and started, then got this. Can't connect with an app and can't get back to the console. Did I do something wrong?

![mtg](https://user-images.githubusercontent.com/60762244/73989504-cc85c780-4967-11ea-9618-06b9b80781f8.png)

**Comment by 9seconds** [comment]
How do you try to connect to this app? Please start in debug mode. Every connection produces some logs so if app still keeps silent, it basically means that your client cannot connect to it at all.

You can't get back to the console because app does not daemonize itself. Please use systemd unit or something like that to run app. Docker is also an easy option.

**Comment by haoren61** [comment]
Sorry, but I'm new to Linux, so not sure how to do it all. I also used docker to start it, then got the same result.
I've solved the prolem by using the oneliner. I can change some parametres in run.sh to set a website for fake TLS and others, right?

Thanks for your reply.

**Comment by 9seconds** [comment]
Yes, of course. This script is no magic :)
