### ISSUE TITLE
Is it possible to set MTG-FakeTLS behind NGINX?

### ISSUE THREAD

**Issue by thematrixdev** [9seconds/mtg#162]
Currently I have NGINX setup accepting connection from Cloudflare (with strict SSL setting). Setting MTG MTG_CLOAK_PORT as 9443, and make NGINX listening at 9443 does not work. I suspect It is due to Cloudflare SSL setting. May I know if I can reverse proxy the connection from Cloudflare to NGINX to MTG instead?

Thanks.

**Comment by 9seconds** [comment]
Yes, please see this instruction: https://github.com/freejohn123/mtproto-tls-server

**Comment by alsotang** [comment]
As long as I investigate, it is not possible to use cloudflare. Cloudflare only proxy http/https stream, but mtproto is not.
Of course you can set mtg behind nginx. but the mechanism is not `client -> http/https -> nginx -> mtg`, it is `client -> mtproto -> nginx with proxy protocol -> mtg`. In this chain, nginx acts as a tcp load balance but not HTTP reverse proxy.

I also wanna set mtg behind cloudflare but current mtproto do not allow this. hope that mtproto would support HTTP or ws in the future.

**Comment by zQueal** [comment]
I have a similar setup.

I have a VPS running caddy that I use to host my domain apex, and to use as a reverse_proxy for docker containers and other services. I'm behind cloudflare, but the `acme_dns cloudflare` caddy plugin is compiled and working properly.

I've been using mtg for a long time and it recently stopped working after I upgraded Ubuntu. Not right after, it took like a few days, which was really really weird...

But I took the opportunity to migrate to a docker container. It took me hours, but I eventually got it to work... And then it stopped... Nothing changed, it just stopped working after like an hour. Since then I've been completely and hopelessly lost getting it started again. I've tried direct ports and the docker container name, and nothing works.

I've additionally added a new A record for my subdomain and ensured it was pointed at my VPS over my wildcard. So I've tried with and without cloudflare, and nothing has worked. It's absolutely crazy.

**Comment by Heshmatkhah** [comment]
> Yes, please see this instruction: https://github.com/freejohn123/mtproto-tls-server

Hi
The mentioned repository no longer exists.
Can you provide a guide on how to share 443 of the host with other services like Nginx or Traefik

I have a Traefik reverse proxy on my host that uses port 443, other services like nginx, open-connect, ... are behind that, I know nothing about Fake TLS, Please help me, thank you.
