### ISSUE TITLE
Basic parent/upper proxy support

### ISSUE THREAD

**Issue by MijazzChan** [9seconds/mtg#165]
Hi, I totally understand and support your idea on not turning the light-weight `mtg` proxy into a complex one.  #113 
However the `mtg <->telegram`  problem still stands out...(at least for me, in China).

Noticing that [v2fly mtproto config](https://guide.v2fly.org/app/mtproto.html) has flaged that mtproto version in `v2ray` is outdated/insecured(It uses mtproto v1).(This part only exists in the Chinese version of the page.)
I, for example, a v2ray/v2fly user, configures proxy in a safe way like `client <-LAN if home/OPENVPN if outside-> v2ray socks5 <-> v2ray server <-> Internet` . 

It will be so convenient that `mtg` has a simple basic support for socks5/https parent proxy. (Since most mtproxy projects, including the official one, haven't provided this kind of feature.)

I can foresee the convenience of `client <->mtg <-> socks5/https <->(Let v2ray handle) <->Internet`. (It frees the step of the OPENVPN or other secured middle-proxy, cuz `mtg mtproto v2,v3` already did a good job at that.)

Best regards.

**Comment by 9seconds** [comment]
Hey. Sorry for the long delay.

The problem itself is not about proxy chaining. The problem is that we can't do that because of telegram. The thing is: proxy IP address matters. And Telegram servers match them. Here is the single nasty line: https://github.com/9seconds/mtg/blob/master/wrappers/packetack/proxy.go#L40 This line states that we have to tell upstream middle proxies about our ip address. And they actually match this data. At least, it was truth the whole 2018 (and pain for debugging).

But at the same time, we do have an ability to build proxies with direct connectivity. It would be possible to build it there. So, if I'll try to support it, it will potentially work only with direct connections. I haven't tried tbh, worth to investigate.

Unfortunately, I do not have a time to check it now but I'll try to make it probably after a new year.

**Comment by MijazzChan** [comment]
Thx for replying. Forgive me for not sensing the real matter here.😥 Still, the `mtg` itself is a really amazing work. I'll keep following for the upcoming releases/features. Thank you.
