### ISSUE TITLE
Socket options

### ISSUE THREAD

**Issue by database64128** [9seconds/mtg#229]
In https://github.com/9seconds/mtg/blob/master/network/sockopts.go:

1. Why change read/write buffer size? The Linux kernel automatically chooses the best buffer size for TCP sockets. Set the buffer size to some arbitrary value is only going to cause problems.
2. Why disable TCP Keep Alive? Go enables TCP Keep Alive by default to evict dead TCP connections. The latest v2 release has a broken "circuit breaker". Without TCP keepalive, dead TCP connections accumulates overtime. It only takes about a week for my mtg instance to reach the default maximum 4096 connections limit.
3. Why disable `TCP_NODELAY` for outgoing connections? If you want to reduce the number of packets as much as possible, set `TCP_CORK`. Disabling `TCP_NODELAY` is not going to help with anything.

**Comment by 9seconds** [comment]
1. You can consider it as a legacy stuff people like. In the past we've been tuning this parameter a lot in order to find out the best performance and different people had different best settings. But nowadays I'm also skeptical about its usefulness. I'm going like to deprecate these settings soon.
2. I didn't find it is working reliably well with mobiles. At least 1 year ago my personal proxy I'm using everyday has accumulated a lot of connections because of that. So, I've disabled keepalives and used quite barbarian but effective technique: https://github.com/9seconds/mtg/blob/master/mtglib/internal/relay/conn.go Roguhly speaking, each connection will be aborted if there is no any incoming/outgoing message in the wire. Actually, I dislike it as well and this is one of the mtg piece that still bugs me a lot. I plan to retest and rework it after new year's eve, or at least to retest if it is still useful. Btw, what do you mean by a broken circuit breaker? Circuit breaker is active only and only if you are using multiple socks5 proxies to avoid dialing up for a proxy that is badly behaves. I also quite surprised by accumulated TCP connetions. Each connection is explicitly closed after some random time. This is quite rare if connection lives longer than 5-6 minutes.
3. Do not remember all details but I've met a couple of bugs with `TCP_CORK`: roughly speaking, connection didnt' closed correctly.

**Comment by database64128** [comment]
> Btw, what do you mean by a broken circuit breaker? Circuit breaker is active only and only if you are using multiple socks5 proxies to avoid dialing up for a proxy that is badly behaves.

Sorry, I only glanced at the code, mostly the comments, so I misunderstood its purpose.

> I didn't find it is working reliably well with mobiles. At least 1 year ago my personal proxy I'm using everyday has accumulated a lot of connections because of that.

In my experience, I found TCP keepalive to be quite effective in evicting dead TCP connections on my Shadowsocks server. Did you experience that before TCP keepalive was enabled by default on Go in https://github.com/golang/go/commit/5bd7e9c54f946eec95d32762e7e9e1222504bfc1?

> Do not remember all details but I've met a couple of bugs with `TCP_CORK`: roughly speaking, connection didnt' closed correctly.

Why actively disable `TCP_NODELAY` though?

**Comment by 9seconds** [comment]
I do not recall all details about keepalives, to be honest. But it could be I need to recheck. If I won't detect any new issues, I'll immediately remove this hack with harsh connection drops. This hack is a source of many performance related problems so mtg will benefit from that a lot. I'm going to check that on the next few weeks. Can't commit because I have a busy time on my daily job. 

I really like the idea of Nagle algorithm because it solves possible issues with environments where last mile is unstable and unpredictable, like mobile connection when your phone can toggle between edge, lte and 3g with a high frequency. Such environment implies usual packet loss so any algorithm that minimizes a number of TCP and packets sounds like a good idea to me. At the same time, I see no reasons of having it in Wi-Fi or Ethernet connection, this is where TCP_NODELAY shines undoubtedly.
