### ISSUE TITLE
Upload video or image very slowly

### ISSUE THREAD

**Issue by hyahm** [9seconds/mtg#265]
Slow sending and fast receiving

**Comment by 9seconds** [comment]
Have you spotted it with a fresh release or it is a long-standing issue?

**Comment by hyahm** [comment]
I maked in this log commit
```
commit 0e8022299057b6e5f9aa6b342af5a84d768e1fea
Merge: f192a71 c07e3d5
Author: 9seconds <nineseconds@yandex.ru>
Date:   Mon Mar 21 16:14:15 2022 +0300
```

**Comment by 9seconds** [comment]
I've tried to send/upload different images and videos today and haven't found any good correlations. Some pictures were uploaded as without any proxies at all (~3mb < 2-3 seconds), many videos were uploaded with a comparable speed. I'm not sure if I can do anything about it at this certain moment. It is very possible that this is not an issue of mtg itself, but about Telegram cluster.

If you can share any details, I would appreciate that, otherwise it will be hard for me to find a root cause out :/

If you can try other implementations like https://github.com/alexbers/mtprotoproxy or https://github.com/seriyps/mtproto_proxy with direct mode (i.e, **without adtag**) and compare performance, it can help.

**Comment by hyahm** [comment]
https://t.me/proxy?server=47.244.47.130&port=3128&secret=ee367a189aee18fa31c190054efd4a8e9573746f726167652e676f6f676c65617069732e636f6d   

you can  get    `scs client`   from   https://api.hyahm.com/docs/scs/#/

overwrite config file  `~/.scsctl.yaml`
```
https://api.hyahm.com/docs/scs/#/
```
node:
  local:
    url:  http://47.244.47.130:11111
    token:  qwer

````

`scsctl   log mtg_0`  to show real-time log

**Comment by 9seconds** [comment]
Unfortunately, I do not have a time for such debugging now :( If you can reproduce and share logs, I'll appreciate

**Comment by hyahm** [comment]
Today is normal. It may be a network problem

**Comment by v03413** [comment]
> Today is normal. It may be a network problem

哈喽，您好，问下该问题之后你有解决恢复吗？我现在使用相同服务器，搭建对比 socks5速度正常，但是 mtg 聊天&图片正常，下载 apk 文件却非常慢、慢到可怕。

**Comment by 9seconds** [comment]
@v03413 unfortunately, the reason of that is not known by me

**Comment by Odinman** [comment]
> 

Same problem, when downloading large files, it is very slow

**Comment by Odinman** [comment]
> > Today is normal. It may be a network problem
> 
> 哈喽，您好，问下该问题之后你有解决恢复吗？我现在使用相同服务器，搭建对比 socks5速度正常，但是 mtg 聊天&图片正常，下载 apk 文件却非常慢、慢到可怕。

Same problem, when downloading large files, it is very slow
