### ISSUE TITLE
Problem downloading files

### ISSUE THREAD

**Issue by jadolg** [9seconds/mtg#274]
It seems there's an issue downloading certain files. Small files seem to work just fine but with big ones it doesn't even start.

**Comment by 9seconds** [comment]
I also see that (same story as https://github.com/9seconds/mtg/issues/270). Apparently, a debug build shows that for some reason Telegram does not reply after a request. The reason is unclear and I've heard a claim that it is only MacOS/iOS related issue. Are you also using iOS?

At this certain moment there is not that much I could do about it unfortunately

**Comment by jadolg** [comment]
It happened for iOS for me but a friend using the Windows client also had issues.

**Comment by jadolg** [comment]
I will close this issue because it duplicates #270
