### ISSUE TITLE
Temporary unavailability on restart

### ISSUE THREAD

**Issue by ilyaglow** [9seconds/mtg#72]
Hey there,

After restarting the proxy it becomes unavailable for a couple of minutes. Telegram client app sees `Connecting...` and not a failed connection error. I should mention that my server does have connectivity with ipv6 telegram servers only, so I assume mtg tries to connect to ipv4 servers first, which can cause the problem.

Some time in the past mtg had `MTG_USE_IPV6` environment variable option and everything was fine,  btw.

**Comment by 9seconds** [comment]
Thanks, I'll try to investigate that. Could you please share logs with enabled debug mode? I need to see how proxy tries to connect to ipv6 telegram servers.

Just wild guess: if you have adtag and connect to middle proxies, then you cannot use the proxy to tunnel ipv4 to ipv6 due to the MTPROTO proxy protocol. So, ipv4 clients are able to connect to ipv4 servers only; ipv6 clients - to ipv6 hosts.

If you do not use adtag, then I probably need to find out another list of ipv6 hosts for direct access. Right now it is hardcoded.

**Comment by ilyaglow** [comment]
When I start the proxy in normal or debug mode it keeps silent for some time and looks like it doesn't do anything. After a couple of minutes, it works like everything is okay and I see successful reads and writes to stream between telegram ipv6 remote address and mine.

I did strace on it a little and noticed at the very beginning that the proxy tries to connect to ipv4 hosts one by one and gives up when connect timeout reached.

I added a few dumb reject iptables rules, so at least I do not wait for timeout to occur and ipv6 address is picked up sooner.

**Comment by 9seconds** [comment]
Yes, we try to access hostname with both protocols due to the support of [happy eyeballs](https://tools.ietf.org/html/rfc6555) so this explains this behavior. Also, current dial timeout is capped by 10 seconds (https://github.com/9seconds/mtg/blob/master/telegram/dialer.go#L14) so to be honest, I'm not sure why we have this 1 minute. I cannot reproduce this problem :/

> I do not use adtag, because it needs ipv4 connectivity with telegram servers as I can see (or I just can't make it work right). I use ipv6 tunnel broker btw.

I think that it does not work because of ipv6 tunnel broker. This is a part of handshake proxy protocol part, where we need to know the exact IP address of the client IIRC (haven't touched that part of the code for a long time) so probably we have information mismatch somewhere there.

Could you please try without ipv6 tunneling, will you see that behavior?
