### ISSUE TITLE
Cannot parse obfuscated frame: Unknown protocol: Unknown handshake protocol

### ISSUE THREAD

**Issue by bao3** [9seconds/mtg#88]
my command is:
`mtg-freebsd -p 10010 -s ddde0ba5f1cba1e3te9b4a7c9b19f89418` 

My telegram client could use this proxy to chat, but I would get the error often ,it's boring.

```
{"level":"error","ts":15617386.8392577,"logger":"main","msg":"Cannot initialize client connection","connection_id":"28a58829-aa90-48af-803a-2e314a5c1e26","error":"Cannot parse obfuscated frame: Unknown protocol: Unknown handshake protocol","errorVerbose":"/home/vagrant/safe/go/src/github.com/9seconds/mtg/mtproto/connection_options.go:86: Unknown handshake protocol\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/obfuscated2/obfuscated2.go:40: Unknown protocol\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/client/direct.go:43: Cannot parse obfuscated frame"}

```

**Comment by AminKaedi** [comment]
Same error here
```
{"level":"error","ts":1561918615.3142095,"logger":"main","msg":"Cannot initialize client connection","connection_id":"ccfea5ce-9e72-4978-a1d4-1465e5ea6ab4","error":"Cannot extract frame: Cannot extract obfuscated header: read tcp 172.17.0.2:3128->IP:57601: i/o timeout","errorVerbose":"read tcp 172.17.0.2:3128->IP:57601: i/o timeout\ngithub.com/9seconds/mtg/obfuscated2/frame.go:87: Cannot extract obfuscated header\ngithub.com/9seconds/mtg/client/direct.go:38: Cannot extract frame"}
```

**Comment by 9seconds** [comment]
@bao3 this error means that your client does not send correct handshake bytes so proxy is not able to serve this request. Why? I do not know.

@AminKaedi keyword in your error is `read tcp 172.17.0.2:3128->IP:57601: i/o timeout`. It means that you've opened the connection to the proxy but did not send handshake bytes there. Proxy expects to get the defined number of bytes (handshake) in order to start to serve your request but it does not get it for some reason. Maybe someone just established the connection to the proxy and send nothing there.

**Comment by AminKaedi** [comment]
@9seconds Thanks for your reply. However, how this problem can be fixed?, I have already tested on **TelegramX** and **Linux Telegram Desktop** clients, Is there something wrong with my clients?
Recently, I figure out that this problem appears only in certain ISPs

**Comment by 9seconds** [comment]
> Recently, I figure out that this problem appears only in certain ISPs

I suppose this might be a reason. IIRC, Iran tries to limit the usage of Telegram and does some attempts to detect proxies. So, it is very possible that these errors come from the ISP or some government organizations.
