### ISSUE TITLE
Fake TLS Proxy

### ISSUE THREAD

**Issue by SimWhite** [9seconds/mtg#95]
Hello. Do you have any plans to add Fake TLS Proxy support?

**Comment by 9seconds** [comment]
Yes, guys, I gonna support it. I've actually already started to do that and realized that the project requires some refactoring before I'll introduce yet another tunneling for client connection. So, right now I'm refactoring the project (approximately I did about 50% this week) and after that, I gonna implement TLS-tunneling.

My plan is also to make the 2nd attempt for connection multiplexing for proxies with adtags but if I fall down into rabbit hole again, I'll postpone it.

So, my rough ETA is 2-3 weeks.

**Comment by z991238** [comment]
这个新开发是否可以是一键式交互式脚本，方便我们在不了解代码的情况下轻松安装，谢谢。这个新开发是否可以是一键式交互式脚本，方便我们在不了解代码的情况下轻松安装，谢谢。

> 是的，伙计们，我会支持它。我实际上已经开始这样做，并意识到在我为客户端连接引入另一个隧道之前，该项目需要进行一些重构。所以，现在我正在重构这个项目（大约我本周做了大约50％），之后，我将实施TLS隧道。
> 
> 我的计划也是用adtags进行代理连接多路复用的第二次尝试，但如果我再次陷入兔子洞，我会推迟它。
> 
> 所以，我粗略的ETA是2-3周。

Whether this new development can be a one-click interactive script, so that we can easily install without knowing the code, thank you. Whether this new development can be a one-click interactive script, so that we can easily install without knowing the code, thank you. Because he is very good in mainland China.

**Comment by 9seconds** [comment]
Well, 2-3 weeks was quite a rough estimation, because I had to concentrate on my primary work. This still ongoing and I plan to finish it anyway. Please see a current progress on `next` branch

**Comment by hookzof** [comment]
You need an example of a tls launch, it's not quite clear.

`./mtg proxy xxx yyy -b 0.0.0.0:443` it's works.

**Comment by 9seconds** [comment]
@hookzof fake TLS is not completely implemented. Stay tuned, it is coming!

**Comment by gudvinr** [comment]
IMO you really shouldn't pass host in this weird way by encoding into key.

It has different meaning than "part of the key" and quite misleading since other parameters are configurable by CLI params and this one isn't.

Probably something like `--cloak_host="google.com:443"` would be a lot more convenient.

**Comment by gudvinr** [comment]
IMO you really shouldn't pass host in this weird way by encoding into key.

It has different meaning than "part of the key" and quite misleading since other parameters are configurable by CLI params and this one isn't. MTG even trims this key down to `SimpleKeyLength` on load.

Probably something like `--cloak-host="google.com:443"` would be a lot more convenient.

**Comment by 9seconds** [comment]
Thanks, @gudvinr. Unfortunately, this key format is a part of the protocol. The client extracts domain name from such key in absolutely the same way. So, even if it can look misleading (tbh, I'm not sure why), this is how both proxy and client work if they want to talk with each other.

**Comment by gudvinr** [comment]
I see now, thanks. Though I didn't find any explanation for this until now.
Can you add this into README for the sake of clarity?

> I'm not sure why

If you don't know _already_ how this works, it looks like any other hex-encoding stream and not `ee + <secret> + <hex-encoded domain name string>`.

**Comment by 9seconds** [comment]
> If you don't know already how this works, it looks like any other hex-encoding stream and not ee + <secret> + <hex-encoded domain name string>.

This phrase makes no sense to me. What are you trying to tell me?

> I see now, thanks. Though I didn't find any explanation for this until now.
> Can you add this into README for the sake of clarity?

Please feel free to make PR.
